### ISSUE TITLE
[Bug]Calling API get_friends 报错 pydantic.error_wrappers.ValidationError: 5 validation errors for Profile

### ISSUE THREAD

**Issue by UKMeng** [nonebot/adapter-red#13]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个Bug

# Bug

## 问题

Calling API get_friends 时有些qqnt的版本(日志使用的是Linux版本的3.1.2-13107）不同返回的参数会有不同，导致有些版本因为数据缺失而报错

## 如何复现

调用get_friend API

## 使用环境:
- 操作系统 (Windows/Linux/Mac):MacOS
- Python 版本: 3.10
- Nonebot2 版本:2.1.0
- Chronocat 版本: 0.0.46 （0.0.45也是同样的错误）
- adapter-red 版本：0.5.0 （之前也是同样的错误）
- 是否使用 `BetterQQNT`: 是

## 日志/截图

```
09-25 20:01:29 [DEBUG] nonebot | RedProtocol | Calling API get_friends
09-25 20:01:29 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/internal/driver/driver.py", line 169, in _run_hook
    await asyncio.gather(*coros)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/utils.py", line 187, in run_coro_with_catch
    return await coro
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot_plugin_saa/utils/auto_select_bot.py", line 31, in _
    await refresh_bots()
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot_plugin_saa/utils/auto_select_bot.py", line 62, in refresh_bots
    targets = await list_targets(bot)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot_plugin_saa/adapters/red.py", line 184, in list_targets
    users = await bot.get_friends()
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/bot.py", line 239, in get_friends
    return [Profile.parse_obj(data) for data in resp]
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/bot.py", line 239, in <listcomp>
    return [Profile.parse_obj(data) for data in resp]
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 5 validation errors for Profile
extStatus
  field required (type=value_error.missing)
vipFlag
  field required (type=value_error.missing)
yearVipFlag
  field required (type=value_error.missing)
svipFlag
  field required (type=value_error.missing)
vipLevel
  field required (type=value_error.missing)
```

直接调用API返回如下
```
[{'uid': 'u_6CQkgdZjkfikjKbuOkSbdw', 'qid': '', 'uin': '66600000', 'nick': 'babyQ', 'remark': '', 'longNick': 'Hi，我是babyQ，你的智能小伙伴~ （注意认证标识，可别认错人哦\\(^o^)/）', 'avatarUrl': '', 'birthday_year': 0, 'birthday_month': 0, 'birthday_day': 0, 'sex': 1, 'topTime': '0', 'isBlock': False, 'isMsgDisturb': False, 'isSpecialCareOpen': False, 'isSpecialCareZone': False, 'ringId': '', 'status': 0, 'categoryId': 0, 'onlyChat': False, 'qzoneNotWatch': False, 'qzoneNotWatched': False}, {'uid': 'u_xxxx, 'qid': '', 'uin': 'xxxxx', 'nick': 'UKM', 'remark': '', 'longNick': 'xxxxx', 'avatarUrl': 'xxx', 'birthday_year': 20xx, 'birthday_month': xx, 'birthday_day': x, 'sex': 1, 'topTime': '0', 'isBlock': False, 'isMsgDisturb': False, 'isSpecialCareOpen': False, 'isSpecialCareZone': False, 'ringId': '', 'status': 0, 'categoryId': 0, 'onlyChat': False, 'qzoneNotWatch': False, 'qzoneNotWatched': False}, {'uid': 'u_xxx', 'qid': '', 'uin': 'xxx', 'nick': 'カンナ', 'remark': '', 'longNick': '', 'avatarUrl': 'x', 'birthday_year': 0, 'birthday_month': 0, 'birthday_day': 0, 'sex': 0, 'topTime': '0', 'isBlock': False, 'isMsgDisturb': False, 'isSpecialCareOpen': False, 'isSpecialCareZone': False, 'ringId': '', 'status': 10, 'categoryId': 0, 'onlyChat': False, 'qzoneNotWatch': False, 'qzoneNotWatched': False}]
```

**Comment by RF-Tar-Railt** [comment]
你再测一下get-groups，get-members这些，看有哪些缺了字段

**Comment by UKMeng** [comment]
get_groups好像没有问题，但是get_members 直接调用api我可能写错了
```python
data = {"group": 'xxx', "size": 200}
url = "http://xxx:16530/api/group/getMemberList"
response = requests.post(url, headers=headers, json=data)
data = response.json()
```
这样我写出来只获得了`[{'index': 0}, {'index': 1}, {'index': 2}]`，只有人数是对的上的，想请教下我是不是哪里写错了
