### ISSUE TITLE
[Bug]: MemberAddEvent处理报错

### ISSUE THREAD

**Issue by qn8524king** [nonebot/adapter-red#27]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个 Bug
- [X] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.8.16

### NoneBot 版本

2.1.1

### 适配器

0.6.1

### 协议端

0.0.52

### 描述问题

使用on_notice，监控MemberAddEvent消息

### 复现步骤

1.on_notice注册一个事件
2.消息函数中处理MemberAddEvent对应event参数

### 期望的结果

可以正确处理MemberAddEvent

### 截图或日志

10-28 21:20:25 [ERROR] nonebot | RedProtocol | Error while process data from websocket ws://127.0.0.1:16531/. Trying to reconnect...
Traceback (most recent call last):
  File "D:\kmrbot\venv\lib\site-packages\nonebot\adapters\red\adapter.py", line 150, in _handle_event
    event = target.convert(event_data)
  File "D:\kmrbot\venv\lib\site-packages\nonebot\adapters\red\event.py", line 295, in convert
    raise ValueError("Invalid legacy invite message.")
ValueError: Invalid legacy invite message.

**Comment by qn8524king** [comment]
我直接把正则匹配改成了r'.*jp="(\d+)".*jp="(\d+)"' ，就正常了
但是当我直接使用.finish(XXXX)结束的时候会在下图的位置报错，提示以下两个参数没有
![image](https://github.com/nonebot/adapter-red/assets/49012015/7654e6b4-a166-447e-806a-bec32af3f2f8)

但是好像MemberAddEvent里这两个参数是有的？我直接屏蔽if判断后也可以正常发送出消息来
![image](https://github.com/nonebot/adapter-red/assets/49012015/66149536-fc62-4b79-b236-d320a607dc54)
