### ISSUE TITLE
[Bug]: MessageSegment.image()报错

### ISSUE THREAD

**Issue by Dragon-ts** [nonebot/adapter-red#33]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个 Bug
- [X] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.10

### NoneBot 版本

2.0.1

### 适配器

0.5.1

### 协议端

0.0.52

### 描述问题

MessageSegment.image()中使用url发送会报错

### 复现步骤

```py
url = baidu.com #只是举个例子
MessageSegment.image(url)
```
这样会报错errno22

### 期望的结果

正常发送图片

### 截图或日志

`Traceback (most recent call last):
  File "C:\shenmeshenme\__init__.py", line 247, in func_
    var = MessageSegment.image(Path(i))
  File "C:\Program Files\Python310\lib\site-packages\nonebot\adapters\red\message.py", line 57, in image
    file = file.read_bytes()
  File "C:\Program Files\Python310\lib\pathlib.py", line 1126, in read_bytes
    with self.open(mode='rb') as f:
  File "C:\Program Files\Python310\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
OSError: [Errno 22] Invalid argument: 'https:\\www.shenmeshenmewangzhan\\shenme.jpeg'`

**Comment by RF-Tar-Railt** [comment]
red只能用本地文件路径或者二进制数据发图片
你应该先拉取url的数据，再用image(data)发送
