### ISSUE TITLE
[Bug]使用系统代理时无法发送消息

### ISSUE THREAD

**Issue by crosage** [nonebot/adapter-red#34]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个Bug

# Bug

## 问题

配置系统代理后无法发送消息，不配置可以正常发送

## 如何复现

设置代理后任意一条消息也无法发送

```python
from pathlib import Path

from nonebot import on_command
from nonebot.adapters.red import Bot
from nonebot.adapters.red.event import MessageEvent
from nonebot.adapters.red.message import MessageSegment


matcher = on_command("test")

@matcher.handle()
async def handle_receive(bot: Bot, event: MessageEvent):
    await matcher.finish("aaaaaaaaaaa")
```

## 预期行为

配置setup.proxy还是会出502，预期是正常发送消息

![image](https://github.com/nonebot/adapter-red/assets/90540469/72ec3921-0802-497f-8d7b-25feedc3f3bc)

## 使用环境:
- 操作系统 (Windows/Linux/Mac):
windows
- Python 版本: 
Python 3.10.1
- Nonebot2 版本:
2.1.2
- Chronocat 版本: 
0.0.52
- Red 适配器版本:
nonebot-adapter-red          0.7.4

## 配置文件

```dotenv
```

## 日志/截图

![image](https://github.com/nonebot/adapter-red/assets/90540469/b559b06e-2487-4467-a7eb-9deb30ce502a)

```
12-03 19:36:06 [ERROR] nonebot | Running Matcher(type='message', module=red.plugins.pixiv.pixiv_from_library, lineno=9) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\crosa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\crosa\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\crosa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\crosa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\crosa\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\bot\red\red\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\red\red\red\plugins\pixiv\pixiv_from_library.py", line 13, in handle_receive
    await matcher.finish("aaaaaaaaaaa")
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 570, in finish
    await cls.send(message, **kwargs)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 554, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\adapters\red\bot.py", line 239, in send
    resp = await self.call_api(
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 123, in call_api
    raise exception
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\adapters\red\adapter.py", line 250, in _call_api
    return json.loads((await self.request(request)).content)  # type: ignore
  File "D:\bot\red\red\.venv\lib\site-packages\nonebot\adapters\red\adapter.py", line 265, in request
    raise ActionFailed(
nonebot.exception.ActionFailed: ActionFailed("HTTP status code 502 response body: b''")
```

**Comment by RF-Tar-Railt** [comment]
把代理路由配置里面localhost走直连
